language: node_js
node_js:
  - "11"
dist: xenial
sudo: required

addons:
  apt:
    packages:
      - google-chrome-stable
    sources:
      - google-chrome

cache:
  directories:
    - ./node_modules

install:
  - cd src
  - npm i

before_script:
  - npm install -g @angular/cli

script:
  #  - ng test --watch false -cc
  #  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - ng build --prod --base-href https://JHSRobo.github.io/copilot-page/
